# Generated by Django 4.0.4 on 2022-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_No', models.CharField(max_length=10)),
                ('comment_dropdown', models.CharField(choices=[('Compliment', 'Compliment'), ('Complaint', 'Complaint')], default='Compliment', max_length=30)),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
    ]
