# Generated by Django 4.0.4 on 2022-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=30)),
                ('account_No', models.CharField(max_length=10)),
                ('services_Types', models.CharField(choices=[('Cash Pickup', 'Cash Pickup'), ('Cash Delivery', 'Cash Delivery')], max_length=30)),
                ('amount', models.CharField(choices=[('5000', '5000'), ('10000', '10000'), ('15000', '15000'), ('20000', '20000')], default=5000, max_length=30)),
                ('email_ID', models.EmailField(max_length=20)),
                ('mobile_no', models.CharField(default='', max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('i_Agree_to_the_Terms_and_Conditions', models.BooleanField(default=True)),
            ],
        ),
    ]
